### ISSUE TITLE
Not working as expected with react-hot-loader

### ISSUE THREAD

**Issue by jimdebeer** [faceyspacey/react-universal-component#100]
when using this together with hot loader components always get re-rendered this is ok in most cases, but when you use this with a scrollbar its a bit annoying - do you plan to make it play nicely together in the future?

**Comment by faceyspacey** [comment]
It’s worked nicely with React hot loader since the start. There are a lot of factors that go into play with React hot loader and perhaps recent webpack changes have broken it, perhaps it’s unique to your setup. If you like doing some research, I’d setup the most basic scenario and isolate the problem to see if it’s unique to your setup. Update the boilerplate to look like your setup in terms of config and package versions.

**Comment by jimdebeer** [comment]
Ill try to recreate it in the universal boilerplate and send a fork - thx for the fast reply and good to hear that hot loading is a thing 😀

**Comment by Grsmto** [comment]
It works fine for me. You have to *hot export* the imported component again, as explained there https://github.com/gaearon/react-hot-loader/tree/next#code-splitting

**Comment by jimdebeer** [comment]
this works great thx @Grsmto I missed this completely 😨
