### ISSUE TITLE
React ssr streaming and routing

### ISSUE THREAD

**Issue by GuillaumeCisco** [faceyspacey/react-universal-component#101]
Hello there.

I've just tried implementing react ssr streaming with the last emotion-server version `9.0.0` and it works well!

But when accessing one of my routes defined by `universal(import('./my_component'))` I get the common error:
```
Warning: Text content did not match. Server: "interpolated content from server" Client: "Loading..."
```
This error does not appear if I disable the streaming part...

I don't really understand what is going on here and how to fix this. Maybe it's a react related issue with streaming. Or a `redux-first-router` issue?

**Comment by faceyspacey** [comment]
It looks like the client is rendering the page before it has the corresponding chunk.

**Comment by faceyspacey** [comment]
The boilerplates don’t have this issue. The JavaScript scripts are supposed to be loaded in order. So if your main script which triggers the first render comes after chunks, all should be fine.

So either the order is incorrect or maybe you are using some attribute like async or defer or something that no longer respects order.

**Comment by GuillaumeCisco** [comment]
Hum, I wonder. I think I'm not loading something correctly. Hope this issue will help other people when it will be resolved.
Here is a screen when I try to load one of my route `/events`. As you can see, the components is downloaded (And I don't think it should be? As we just refreshed the page, the content should be already available from the server rendering process) after the main js files:
![screenshot_2018-02-07_16-54-28](https://user-images.githubusercontent.com/1155244/35926126-bdfc24f4-0c27-11e8-90a0-1ef3272042bc.png)
![screenshot_2018-02-07_17-09-52](https://user-images.githubusercontent.com/1155244/35926955-c8c5de14-0c29-11e8-890c-5650fd7ab9b3.png)

When the `events/components.js` is downloaded, the error is displayed.



When __removing__ the streaming part:


![screenshot_2018-02-07_17-00-31](https://user-images.githubusercontent.com/1155244/35926493-955a1a1e-0c28-11e8-86a6-741647f8527a.png)
![screenshot_2018-02-07_17-03-3t](https://user-images.githubusercontent.com/1155244/35926717-15929ca6-0c29-11e8-99b6-08581e747288.png)

As I can investigate in the streaming part, the chunk `'events/components'` is not present when the `/events` path is called. Then the `/index.es.js.map` path is called and the chunk is present. That's when the  error is displayed.


The project triggering this is available here https://github.com/GuillaumeCisco/restaurantdelaposte/tree/gcisco-stream (gcisco-stream branch)

The main code about streaming is https://github.com/GuillaumeCisco/restaurantdelaposte/blob/gcisco-stream/src/server/render.js

**Comment by faceyspacey** [comment]
`flushChunkNames()` and `flushChunks()` needs to be run where your `late` stuff is:

move:

https://github.com/GuillaumeCisco/restaurantdelaposte/blob/gcisco-stream/src/server/render.js#L59

to:
https://github.com/GuillaumeCisco/restaurantdelaposte/blob/gcisco-stream/src/server/render.js#L77

You have to do that stuff after the page is rendered. You'll also need to capture the chunk names a in a different way since this can happen asynchronously. We have a `<ReportChunks />` provider component just for this purpose covered at the bottom of this section:

https://github.com/faceyspacey/react-universal-component#flushing-for-ssr

...That leaves one problem: the stylesheets. In short, since they have to render in the head, the only way to figure out what stylesheets to serve is via the path/route. Styled Components and Emotion now have a streaming mechanism to render their styles interleaves with components as they're streamed, but for the various perf benefits related to static stylesheets you're only option is to know which to render via a function that that returns the name of the stylesheet based on the path.

Hopefully that paints the picture of what must be done.

**Comment by GuillaumeCisco** [comment]
Thanks @faceyspacey for taking some time to look about it.
I've succeeded making it works!!! :tada: 

As you pointed out, I moved the `flushChunkNames` scope to the `late` part of the streaming process and it works great!
Regarding the css process, I don't use the css in js chunk philosophy (i.e `import './index.css'`). I only use emotion and I have one main chunk called `main.css` with the global css of the website.
So css chunks are a false problem for me. And streaming works very well now.

Updating my code, I did not need to use `ReportChunks`. Maybe I'll find an issue in the future and will keep this in mind.

Thank you very much again.
Your work is pure gold!

**Comment by faceyspacey** [comment]
Be careful with not using report chunks as I’m pretty sure streams aren’t queued (that’s part of the point—they are async). So that could mean one stream clears the chunk names another stream is relying on.

**Comment by GuillaumeCisco** [comment]
I do not use `clearChunks` either. Is this part mandatory?
I don't understand what is the purpose of this method.

**Comment by faceyspacey** [comment]
The array of chunk names has to become empty before the next request. It’s done automatically in synchronous rendering. With async u need to guarantee two simultaneous requests/renders aren’t contributing to the contents of this array (either adding additional items or clearing)

By using the provider in your case you guarantee a unique array per every request/render, EVEN IF THE REQUEST IS AN ASYNC STREAM.

**Comment by GuillaumeCisco** [comment]
Thank you @faceyspacey for these pieces of information!
I truly understand it correctly now.
Thanks again, I hope it will help others ;)

Cheers,
