### ISSUE TITLE
Nested ChunkNames report a non-existent chunkname

### ISSUE THREAD

**Issue by zackkirsh** [faceyspacey/react-universal-component#117]
Hey James.

Pretty much the same issue i patched in the babel loader around nested chunknames. 

This one was interesting, but logical. Before (in the babel-plugin) I was testing against an import('../something/somethingelse') Which works perfectly because ive got a path to correct. 

Im currently building a rudimentary way for developers to render components in various folders (lets assume we have a relatively simple app and react routing isnt used).

`localhost:3000/component/NestedComponent/SomeComponent`

I match that to a route of `component/*:componentName`
What i end up with is passing `this.props.route` to the my "UniversalComponent" (not to confuse you, ive placed it below)

```
// needs error handling
const determineHowToLoad = (props) => {
    const resolver = (typeof props.component !== 'string') ? props.component() : import(`./${props.component}`);
    return resolver
}

export const UniversalComponent = universal(determineHowToLoad, {

    onError: (error, {isServer}) => { // eslint-disable-line no-unused-vars
        throw error;
    },
    loading: () => null,
    error: (e) => {
        console.error(e); // eslint-disable-line no-console
        return <div/>;
    }
});
```
In the issue im opening, the component is being used like this (just to test)
`<UniversalComponent userId={user.id} component="NestedExample/NestedComponent"/>`
Which is essentially the same as 
`<UniversalComponent userId={user.id} component={this.props.route}/>`

I was using my master branch of the babel plugin, which hadn't yet been updated with your upstream repo. So it immediately didn't work, after pulling from upstream (you) and restarting my server. I got that error about no chunk with this name found and it showed me `Something/SomethingElse`. However, strangely enough, the component was able to load. It just did a strange flash and i also got a checksum warning about the client server output. 

I pulled this repo and went on an investigation, and it looks like, because its a fully dynamic component no path gets generated correctly. when the HOC runs the `chunkname` function.

Looks like the culprit is `const chunkName = addModule(this.props)` 

Ive not yet started to look into this, but ill try and open a PR this week, as well as investigate the folder flattening reported

**Comment by faceyspacey** [comment]
Actually, `props.component()` should work. Honestly it's been a while since I've been on this side of things. But part of the concept here is that you could pass around a single transpiled `import()` statement (i.e. through HoCs) and it would still continue to to work.

As you mentioned, it may have to do with the *"path not being generated correctly." Perhaps if it's happening in a different file or something like this, by the time its synchronously required server-side the path is incorrect. If it was a webpack server, it should be fine, but with a babel server, perhaps it breaks. Something like this may end up being the issue.

**Comment by zackljackson** [comment]
The issue appears related to chunknames no being transpiled with really dynamic nested paths like this. I know im not the best text based explainer of things 😂 Ill investigate it soon and open a PR (if theres actually something to fix), along with (if possible) a example repo of some kind.

I may be wrong but im pretty sure its because Something/SomethingElse gets reported instead of `Something-SomethingElse`, which if this was a `import()` and not a string, you'd see `import(*/chunkname: something-else*/ ../Something/SomethingElse);`

On a side note, is there a more efficient way to communicate in the event it regards something not necessarily worth opening an issue or PR 😂I'm sure you are sought after and surely do not wish to unnecessarily consume your time. I'm trying to secure more time dedicated to universal architecture and chunk splitting, ideally I'd like to become heavily involved in the narrow open source community which is making this possible - mostly around making it more robust and bullet proof, to work at scale on projects as large as 100 million lines of javascript. I'll likely start trying to fix open issues or respond to ones. But beyond that, if theres anything you need a hand in - zackary.l.jackson@gmail.com (personal mail)

**Comment by faceyspacey** [comment]
Sounds good. If you could help me with the rollback and major version bump for the recent PR that would be great. Still waiting on NPM to approve the version unpublishing.

**Comment by zackljackson** [comment]
@faceyspacey Ive gone ahead and opened two PRs, Let me know if I've done it right. If not, let me know your process so I can support you correctly the next time round :)

**Comment by EdonGashi** [comment]
I am getting this problem in 2.9.0

```
<script type='text/javascript'>window.__CSS_CHUNKS__= {"pages-home-Home":"/static/pages-home-Home.css","pages-about-About":"/static/pages-about-About.css","main":"/static/main.css"}</script>
```

[UNIVERSAL-IMPORT] no chunk,  pages/about/About , found in "window.__CSS_CHUNKS__". If you are not serving CSS for this chunk, disregard this message.

**Comment by zackljackson** [comment]
@EdonGashi make sure all universal family components are up to date.Most importantly, the babel-plugin

**Comment by EdonGashi** [comment]
I'm stupid `() => import(/* webpackChunkName: 'about' */ 'pages/about/About')` works just fine.

I was attempting `() => /* webpackChunkName: 'about' */ import('pages/about/About')` and wondered why it the babel plugin ignores chunk names 🤦‍♂️ 

Naming chunks manually is no problem for me. It has the benefit of having shorter strings.

**Comment by faceyspacey** [comment]
Is this solved?

**Comment by zackljackson** [comment]
Pretty much! With webpack 4 upgrades
