### ISSUE TITLE
Server side rendering with Browser API code

### ISSUE THREAD

**Issue by manish4781** [faceyspacey/react-universal-component#133]
Just want to open a discussion on how we can achieve a Server side rendering of an App with having some window API like localstorage or Cookies

I am rendering App component at server and rendering few other component from App component some of my child component contains **Cookies** and **Localstorage** API to store the data, but when i run the App it show window not defined on Server side as window is not available at that time, what is the best way to achieve this and store some values in Client's browser.

**Comment by klaaz0r** [comment]
First thing that comes to mind is define a global like `IS_SSR` or something similar and simply not run code depending on the browser on the server. When the client is hydrated you can of course run the code depending on the browser

**Comment by EdonGashi** [comment]
In these situations I like to keep two separate modules under the same API. The following example is based on koa web server, but if you are using express it shouldn't be too different.

Note: `app` is my source of truth for the application state, which gets serialized and then hydrated in the client. In the server I hook koa's ctx to the app, so that I can access it from modules:

cookie.client.js (browser):
```js
import Cookies from 'js-cookie'
const prod = process.env.NODE_ENV === 'production'

export function getCookie(app, name) {
  return Cookies.get(name)
}

export function setCookie(app, name, value, expires) {
  Cookies.set(name, value, {
    expires,
    SameSite: 'lax',
    secure: prod
  })
}
```

cookie.js (server):
```js
const prod = process.env.NODE_ENV === 'production'

export function getCookie(app, name) {
  return app.__ctx.cookies.get(name)
}

export function setCookie(app, name, value, expires) {
  app.__ctx.cookies.set(name, value, {
    httpOnly: false,
    overwrite: true,
    expires,
    sameSite: 'lax',
    secure: prod
  })
}
```

In this way, I can call (pseudocode) `cookies.getCookie(app, 'myCookie')` without worrying about underlying storage. If it's a browser it reads from document.cookie, if it's a server it reads from request headers.

**Comment by ScriptedAlchemy** [comment]
`universal-cookie` ?
