### ISSUE TITLE
Does not work when chunkName is not identical with what babel plugin generates when using flushChunkNames()

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/react-universal-component#15]
I am trying to break down a few issues in all these packages to try to improve docs or just understand it better on my own.

One thing I noticed is that the `chunkName` I assign in options has direct influence on the file names being produced - I figure that's used for the `[name]` part of the chunkFilename. That makes one thing quite unfortunate: the output matches the file structure and naming of the sources e.g. when importing `./views/main/Main` the chunkName generated by the Babel-Dual-Import-Plugin is `views/main/Main` which produces and output inside the build folder of `views/main/Main.js+css`. 

What I like to have instead is a flat structure of files inside the build directory. I assumed that I can just change the `chunkName` part inside the `universal` options but unfortunately this does not work. It even breaks - without any warning. It just seems to be unable to match the `chunkNames` to the files correctly and ignores the affected universal module.

Interestingly it seems to be possible to fix at the this last issue by using `flushModuleIds()` instead of `flushChunkNames()` from the server part of this library. I wonder why we chose one or another.

**Comment by swernerx** [comment]
The same documentation issue between

```
flushChunks(stats, {
  moduleIds: ReactUniversalComponent.flushModuleIds(),

  // or:
  // chunkNames: ReactUniversalComponent.flushChunkNames(), // not both
```

is also visible here: https://github.com/faceyspacey/webpack-flush-chunks#options-api

It just says do not use both. Here it prefers ModuleIds... in some other examples the code is based on `flushChunkNames`.

Maybe you are able to clarify a bit. Thanks!

**Comment by swernerx** [comment]
Interestingly as I said: when using `flushModuleIds()` the name does not need to be identical which makes things easier. If this is working the same as `flushChunkNames()` for other cases I figure we should settle to just one API.

BTW: Interestingly the rendered chunk names then use the `chunkName` from the `universal` options while the `__CSS_CHUNKS__` refer to the auto-detected one by the babel-plugin. Confusing stuff.

**Comment by swernerx** [comment]
It seems like the whole `chunkName` option on `universal()` is fully optional when using `flushModuleIds()` instead of `flushChunkNames()`. While the first works stable, the last one breaks as soon as individual `chunkName`s are missing.

**Comment by faceyspacey** [comment]
There are several reasons for chunk names over module ids:

- `importCss(chunkName)` -- when we don't know the chunk name (and only the magic webpack-flush-chunks stuff does) we can't grab the css files by chunk name
- `flushModuleIds()` is significantly more server-side work than `flushChunkNames`, which was one of the driving factors for moving toward a chunk name approach. Why eat up so many cycles in your cluster of servers when you don't have to.

> Interestingly the rendered chunk names then use the chunkName from the universal options while the __CSS_CHUNKS__ refer to the auto-detected one by the babel-plugin.

The chunkName option has to match. If they don't, you won't embed the correct chunks in your HTML. The real name is the one generated by the babel-plugin. babel-plugin-univesal-import will create this for you, so soon you won't have to worry about this.

> What I like to have instead is a flat structure of files inside the build directory.

Webpack creates sub directories when there are slashes in the chunk name. The system has been designed to support this:

```js
universal(props => import(`./pages/${props.page}`))
```

Likely now you are creating many components like this instead:
```js
universal(()=> import(`./pages/Page123`))
```

and then assigning them to keys on a hash, and then determining which to show. The goal is to move beyond that like you can see in this client-only environment:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox/tree/master/?module=SJoGXS87r-

So once I finish my PR to webpack and it's merged and published, we'll be doing that. That's not to say we can't come up with a better flat way to deal with static imports. The challenge is this: if we could create chunk names just based on the file name, we'd do it; but we can't reliably do that because of the rare edge case that you have the same module name in different directories.

So that's the thinking behind a lot of this. I likely could pull off the `flushModuleIds` way with `importCss(moduleId)`. I then need to create a mapping of moduleIds to chunk names and serve that. That will likely take me some time. But more importantly, it means lost of wasted cycles on the server. Truthfully, I may just do it though. It's not like it's tons of cycles. Just for the OCD (like myself), you don't like to know you took that route when there is a quick primarily hash-based route where you primarily just key into `stats.assetsByChunkName`. And by the way you couldn't do that before the "magic comment" feature came out. Webpack Flush Chunks was birthed out of the long way. I was really annoyed to see I wasted all my time making that when a faster simpler way came out. But perhaps in the end we'll have to go back to it. 

In short, you're preaching to the quire when it comes to using `flushModuleIds`. 

Now that all said, the universal-import plugin will mean you rarely use the options, or if you do, it's for a custom `loading` component, `minDelay`, etc. 

----
final note: u made me realize how to do it without moduleIds instead. i'm 99% sure it's 100% possible. now i just gotta find the time. ...perhaps the biggest consideration is that it's nice to have chunks with real names instead of `0.js`. By the way to insure the js chunks get names, u do this in ur webpack config:

```js
output: {
    chunkFilename: '[name].js',
```

if u dont, the name is only "virtual", i.e. it only appears that way in `stats.assetsByChunkName`, but the resulting file still is `0.js`. The css files i create no matter what get the name, but that's cuz i control them, whereas Webpack controls the creation of js chunks. I feel like it should just default to the chunk name, but whatever.

**Comment by faceyspacey** [comment]
And you know what, there's no better thread to discuss/figure_this_out than this one. 

I also just remembered I cache the bulk of the work when using `flushModuleById()`:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L140

which skips all this work on subsequence requests:
https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L148-L173

So it's actually far smaller of a problem than I had in my mind. It's a bit more cycles than using chunk names, but not much. This also simplifies babel-plugin-universal-import quite a bit.

The deciding factor though is whether the tradeoff of having chunks named `0.js` is worth it. It's very useful for people setting this up to see actual chunk names flushed, rather than meaningless numbers. In addition, if you're not using babel on the server, it also simplified things, since it means you didn't need to provide a `rootDir` property. Perhaps I can use the babel plugin to figure that out too.

Another deciding factor is: which is more error-prone. As you found you can't specify your own magic comment. I could add the capability to do that as an override. But that also could have potential problems of its own--it would require you to add `[request]` to chunk names for dynamic imports. And then the babel plugin would have to parse that and generate a chunk name for that. 

The module IDs approach--though I never received any error reports--could under some circumstances not work. Perhaps the way stats is structured in a particular setup will break the way webpack-flush-chunks discovers chunks based on module IDs. Doing less work at this critical juncture when using just a chunk name means more stability here. But at the same time, the babel plugin does more work to make chunk names work. 

It's really a tough call, but because of the caching thing I'm starting to lean towards moduleIds too. I'm gonna need to make this decision soon (like this week). Unfortunately, the only way to make the best decision may be to actually do it and see whose implementation is better. At the end of the day, a simpler implementation is perhaps the number 1 way to prevent problems in userland.

**Comment by faceyspacey** [comment]
...by the way i reverted back to my previous thing (which was the second thinking in the grand scheme of things) to use `chunkNames`. The reasons are:

- since babel-plugin-universal-import provides all options there is now less risk of you writing the wrong `chunkName` option
- flushModuleIds require extra webpack config to make IDs deterministic (hashedModuleIds and namedModuleIds plugins)
- there is a bit more server work using flushModuleIds
- seeing proper names for files rather than `0.js` makes it easier for developers to know the system is working. With numbered chunks you are less likely to know if the correct chunk was served.

**The cons are:**
- nested directories, but that's a matter of perspective. I prefer it. It shouldn't really matter if you automate all this stuff.
- i dont like dealing with the magic comment in the babel-plugin implementation, but this shouldn't be a driving factor.
- if not using the babel-plugin u can easily mess up how u provide the `chunkName` option and the `webpackMode` comment

**Comment by swernerx** [comment]
The directory thing is actually tricky when using more flat-file oriented stores like S3. I wish there would be an option to actually "translate" the chunkName somehow e.g. via some middleware. In my case what helps would be just doing a `str.replace("/", "-")` thing. But hashing could be also useful. Probably we can do this by making the babel plugin configurable... :)

**Comment by faceyspacey** [comment]
But s3 has better support for nested dirs these days. Is it not easy from the command line like the UI has been recently made?

Is your problem that u now gotta sort through directories and upload to the corresponding nesting on s3?

**Comment by swernerx** [comment]
It's effectively that the publishing sync tools we use are still living in the old world of S3.


> Amazon S3 has a flat structure with no hierarchy like you would see in a typical file system. However, for the sake of organizational simplicity, the Amazon S3 console supports the folder concept as a means of grouping objects. Amazon S3 does this by using key name prefixes for objects.

It still a hack. Via: http://docs.aws.amazon.com/AmazonS3/latest/UG/FolderOperations.html 

That said, looking at the code of the plugin, it shouldn't be too hard to add some flexibility here e.g. by letting the plugin user define a custom `createTrimmedChunkName`. Is there anything problematic with this when combining with the other projects e.g. universalComponent? Otherwise I would try my luck offering a PR :)

**Comment by faceyspacey** [comment]
It's doable. We would want to do it as global config so it doesn't have to be transformed out of the options arg. That's a lot of babel plugin work.

Just take a peak at the plugin and see the function where I generate chunk makes. There is 2 one for the magic comment and one for the plain one, as the magic comment includes [request] in the chunk name string to indicate to webpack it's a dynamic require with more than one chunk name.

I have a trimming function. We would just use outside of the babel plugin like importCss is used. importCss has its own separate file. So in this case we would create /trimChunkName.js and in it, it would detect if U set one globally at the start of ur app.

import { supplyTrimFunc } from 'babel-plugin-univerasal-import/trimChunkName'

supplyTrimFunc(func)

It would work with all components though. The options route per universal component takes more time but is doable. It has a caveat which is why I don't wanna do I: React Loadable used to transform things to the options arg but it was impossible to work with user generated HoCs where options are passed to a wrapper function the babel plugin knows nothing about.

**Comment by faceyspacey** [comment]
We would probably be better off parsing a custom magic comment like u originally tried. I gotta think about it

**Comment by faceyspacey** [comment]
That gives us component level + more idiomatic

**Comment by faceyspacey** [comment]
Unless there is something it can't do I'm not thinking of, the magic comment is the answer. 

It has to generate 2 things: the webpackMode and the chunk name we flush. Both are slightly different strings as described above

**Comment by swernerx** [comment]
> We would want to do it as global config so it doesn't have to be transformed out of the options arg. 

What is so wrong about plugin options? I mean we use it in a lot of places right now for presets and plugins in babel e.g. babel-preset-env.

**Comment by faceyspacey** [comment]
The magic comment has to be statically parsed. So the plugin has to discover the option and then put it to use which it can't do if u make ur own wrapper function and pass the options to it from somewhere else in code

**Comment by faceyspacey** [comment]
I'll think of something tho. New angles always open up
