### ISSUE TITLE
SSR not loading synchronously and CSS never loads for SSR page

### ISSUE THREAD

**Issue by eudaimos** [faceyspacey/react-universal-component#16]
@faceyspacey thanks again for the great work.  I'm at a point where I've tried what I believe to be every avenue and just completely stuck.

I'm trying to upgrade to the `babel-plugin-dual-import` but it breaks SSR for `react-universal-component`s only in my production config.  I see 2 symptoms
1. The SSR always comes back with the `Loading...` no matter which route I hit (or which view is universally dynamically included)
2. The styles/css for that page are never loaded, even if I navigate away and back

If I navigate (using `redux-first-router`/`redux-first-router-link`) client-side to a view, the css loads just fine.

I've looked through the issues in your various repos and since I'm not the best at webpack configs, I think I'm at the point of randomly making changes which isn't a great way to troubleshoot.

I'm using `koa` for the server, so I have to translate all of your examples.  We have a hodgepodge mess of CSS at the moment b/c we're using components that include their own global CSS, but that doesn't seem to affect things in dev.

We're using webpack server-side b/c I couldn't get HMR working with just babel early on, however, the major difference between dev and production servers is that due to the hot module server middleware, in dev we are using the render middleware as the entrypoint whereas in production, the server itself is the entrypoint.
Do you think this could be the cause?

Also 2 pieces of advice to improve the DX:
1. The boilerplates need to be kept up with the "latest" developments as I'm not sure which one I should use as the example configuration.
2. Convert all of this to a monorepo so that there is one place for issues and code.  I like the different modularization of the system, but it's very hard to investigate which issues are relevant.

**Comment by faceyspacey** [comment]
yea, im going to be consolidating soon, and removing all but one boilerplate (which will be the redux-first-router boilerplate, even for the *Universal* stuff).

i dont suppose u can just paste your production config and as much relevant code as u can. i realize u likely can't just invite me to a private repo. 

Are you using the babel-loader to strip comments--that could be it. 

What does the transpiled code look like, before webpack re-transpiles it a second time. Open up node_modules/babel-loader, and find right after the code is transformed, and log it. Then when webpack is built, there will be lots of logs in the console. Use the search feature of your terminal to find where `import()` is, and let's take a look at what's generated. Also, for good measure, find the final output generated by webpack as well, and lets look at that. 

Since it works in development, this issue 95% must be a transpilation issue due to webpack/babel config.

**Comment by eudaimos** [comment]
Here's what I can find for the transpiled server code

from:
```javascript
const UniversalComponent = universal(() => import('./Season'), {
  path: path.resolve(__dirname, './Season'),
  resolve: () => require.resolveWeak('./Season'),
  chunkName: 'Season',
  // minDelay: 500,
});
```
ends up as:
```javascript
var UniversalComponent = (0, _reactUniversalComponent2.default)(function () {
  return new Promise(function (resolve) {
    new Promise(function(resolve) { resolve(); }).then((function (require) {
      resolve(__webpack_require__("./src/app/views/Season/Season.js"));
    }).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
  });
}, {
  path: _path2.default.resolve(__dirname, './Season'),
  resolve: function resolve() {
    return /*require.resolve*/("./src/app/views/Season/Season.js");
  },
  chunkName: 'Season'
  // minDelay: 500,
});
```

Here's what I get with the magic comment included, from
```javascript
const UniversalComponent = universal(() => import(/* webpackChunkName: 'Season' */ './Season'), {
  path: path.resolve(__dirname, './Season'),
  resolve: () => require.resolveWeak('./Season'),
  chunkName: 'Season',
  // minDelay: 500,
});
```
to
```javascript
var UniversalComponent = (0, _reactUniversalComponent2.default)(function () {
  return new Promise(function (resolve) {
    new Promise(function(resolve) { resolve(); }).then((function (require) {
      resolve(__webpack_require__( /* webpackChunkName: 'Season' */"./src/app/views/Season/Season.js"));
    }).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
  });
}, {
  path: _path2.default.resolve(__dirname, './Season'),
  resolve: function resolve() {
    return /*require.resolve*/("./src/app/views/Season/Season.js");
  },
  chunkName: 'Season'
  // minDelay: 500,
});
```

Here's what I get when I strip it down:
```javascript
const UniversalComponent = universal(() => import('./Season'));
```
becomes
```javascript
var UniversalComponent = (0, _reactUniversalComponent2.default)(function () {
  return new Promise(function (resolve) {
    new Promise(function(resolve) { resolve(); }).then((function (require) {
      resolve(__webpack_require__("./src/app/views/Season/Season.js"));
    }).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
  });
});
```

**Comment by faceyspacey** [comment]
the dual-import plugin isn't be applied. Notice there is no `Promise.all`. 

Paste your webpack config por favor. If you have comments set to be stripped out by the babel-loader, it won't work. Perhaps you're specifying your babelrc config via the babel-loader and forgetting to add dual-import. 

Another issue could be because you're using https://github.com/airbnb/babel-plugin-dynamic-import-node

What babel presets are you using for production? What about development? Certain presets and plugins like the above one get rid of calls to `import()`. That very well could be it. My guess right now is it has to do with your other babel plugins/presets. 

ps. just released the latest RFR article on data-fetching + middleware:
https://medium.com/faceyspacey/redux-first-router-data-fetching-solving-the-80-use-case-for-async-middleware-14529606c262

**Comment by aga5tya** [comment]
@faceyspacey,, post i migrated to 2.0, i can't get the synchronous rendering to work. The component always has "...Loading" from server. This was working when redux connected component has associated state at initialState during render while on 1.5.0. Is this known one or I'm doing something wrong? Seems to work as expected in the new boilerplate 😕 

Just to add, I am not using webpack at local,, I'm on 3.4.1 since i still don't use props based imports. Is this the issue ? Anything specific I'm missing out on? 

Using Component.preload() on componentWillMount seems to render on server, but client re-renders it and checksum error appears. 😞 

Posted this since the issue looks similar. Let me know if this needs to be on a new thread.

**Comment by faceyspacey** [comment]
@aga5tya glad to hear you pin-pointed the difference in the props stuff vs static imports.

...i dont suppose u can provide a quick repro. it's very important to insure i didnt break anything. It's one of the reasons i havent pressed play on the 2.0 release article. I wanted to see if anyone had any issues just like this. There really shouldn't be tho. But clearly there is lol, if this was working prior to 2.0.

**Comment by faceyspacey** [comment]
....so ur using babel on the server??

**Comment by aga5tya** [comment]
@faceyspacey using webpack both on server and client bundles.. Mostly based on ctrlplusb's react universally with redux added. Il try and give a repro by tomorrow ,, let me know if u need any additional info.

**Comment by faceyspacey** [comment]
what do you mean by this:

```js
Just to add, I am not using webpack at local,, I'm on 3.4.1
```

By the way I recently started a chatroom:
https://gitter.im/Reactlandia/Lobby

feel free to hit me there. ...did u get the invitation from gitter by the way?

**Comment by aga5tya** [comment]
Didn't notice, gitter will definitely help alot 👏 

I meant im using the last published webpack, that still doesn't have your PR changes. I see that boilerplate clones webpack and aliases it. Me being on webpack 3.4.1 has something to do with this..?

**Comment by faceyspacey** [comment]
it shouldn't since ur not using dynamic imports.

are u using the new babel plugin: 

https://github.com/faceyspacey/babel-plugin-universal-import

**Comment by aga5tya** [comment]
Yes,, replaced and followed precisely your commits on boilerplate. I think a repro would really help us both here.. Will do asap.

**Comment by aga5tya** [comment]
Yes,, replaced and followed precisely your commits on boilerplate. I think a repro would really help us both here.. Will do asap.

**Comment by faceyspacey** [comment]
...just cuz i was about to press release the medium article like in the next hour or 2. really dont wanna do that with a known issue floating around.

**Comment by aga5tya** [comment]
I'm actually in travelling ,, and i'm sure its something to do with my configuration since it's not replicable on the boilerplate. So i think u can go ahead with the article.. Cheers 🍻 I'll check again and hit u with repro asap.

**Comment by faceyspacey** [comment]
I'm going to close this, as we solved @aga5tya 's problems on chat. The main problem was that the `webpack-node-externals` package behaves funny. If you follow the precise directions for `externals` in the readme, it solves his issue. Perhaps that was yours issue too, @eudaimos.

Hit me on chat if you need anything. In a few hours the React Universal Component 2.0 article is going out with the new babel-plugin-universal-import which eliminates the ned to manually use `resolveWeak`. @eudaimos  as for the `monorepro` idea, we're a weak off from `universal-render` which will consolidate every single package under only one you have to use.

So things will just keep getting better and easier.
