### ISSUE TITLE
SSR onLoad triggering only once

### ISSUE THREAD

**Issue by eldar-gamisoniya** [faceyspacey/react-universal-component#30]
Hi, James. Amazing work with these packages!
When used on the server side, onLoad event triggered only once (you can check it in the demo by adding console.log to the onLoad event), which makes it impossible to use for adding reducers, etc, as that should be done with each request. I looked at the code, and it seems like modCache could be cleared too with SSR flushing, but maybe a better solution exists).

**Comment by faceyspacey** [comment]
Do you mean "only once" when using dynamic expressions for your import? I.e. only for the first import? Or are you referring to the same import (perhaps via a static expression as the argument, or when revisiting)?

Because `onLoad` is only supposed to be called the first time a module is imported. 

...or I think I get what you're asking--you're saying it's cached between requests. Damn. Your clearing solution sounds about perfect. I'll get to it as fast as I can. Feel free to PR--it sounds like you know exactly what to do. Just clear the cache any time either `flushChunkNames` or `flushModuleIds` is called.

...Actually, after looking at it, it's a bit more complicated. Basically the cache is created in each HoC:

https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L47

So there isn't a global cache like there is for chunkName and moduleId flushing. But it's fine if there was (i'm pretty sure). So we could create that object in the outer module scope, and perhaps just attach it to `options.modCache` for each HoC.

As far as actually *flushing*. You should be able to just re-assign it. But there may be some weird edge case that requires us to delete all the properties off of it. I don't think so though.

**Comment by eldar-gamisoniya** [comment]
As far as i understand, here: https://github.com/faceyspacey/react-universal-component/blob/da3e28708063991f57ba4eb92b8d95a4aa229f39/src/utils.js#L82
not a full module gets cached, but only part selected by the key. It would break in case of global cache if multiple universal components would refer to the same module with different keys (maybe even the only universal component can break now if the `key` is the non-pure function, haven't tested, but theoretically possible).

Also, without local cache, `onLoad` won't be triggered if the second universal component imports the same module but with the different onLoad function. So i think there should be some kind of a global cache that stores modules (not `exp`, like in the `cacheExport`, but the full module) and another cache that stores `onLoad` functions (an array of `onLoad` functions per each chunkName). 

That way, only the cache with `onLoad` functions should be flushed, and will be fixed potential issue when the `key` is not pure.

**Comment by faceyspacey** [comment]
you're right. though it's rare, as most are using the babel-plugin which generates the `chunkName` function. And you're right again regarding different `onLoad` functions, though likely rare.

We have to support such edge cases of course.

I think I have the simplest solution. Basically for each universal component (within the HoC) we have to generate a unique ID. A deterministic one that will be the same on both the client and server. This can be challenging because people may decided to dynamically create universal components at "render time," rather than "statically" at first evaluation.

Either way, what we do is we generate an ID, and then store the `modCache` in a hash of caches by component ID. Then on flushing we iterate through the hash and clear each `modCache` which incidentally is another hash.

I'm going to get to this as soon as I can, but I'm focused on some Redux-First Router stuff. Any help would be much appreciated.

**Comment by faceyspacey** [comment]
ps. funnily enough the babel plugin generates an ID for each component in preparation for future features. The ID is an interesting one:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/__tests__/__snapshots__/index.js.snap#L113

It's essentially the string form of the import, including if dynamic expressions are used. It just never actually interpolates the dynamic expression. So its strength is that its deterministic, but it's weakness is that if another universal component defined in another file performed the same import, it wouldn't share the same `modCache`. However, that may be a good thing, as like you said, different `onLoad` functions would be use. And also, keep in mind that if the imported module/chunk is available, it will be synchronously required. The cache only short-circuits a bit earlier while insuring `onLoad` is only ever called once per universal component. 

So, in conclusion, we have a reliable ID. But it requires you to use the babel plugin. Basically the best thing we could do is this:

- hopefully user uses babel plugin
- require them to manually provide an ID option (we'd need to provide this option)
- fallback to numeric incrementing ID number. Ultimately this is fine since if people are doing things correctly (and most performantly), they aren't generating universal components at *render time*. That means on both the client and server the ID will correctly increment on initial evaluation as the components are created from the hocs. boom, done for 80% of all uses.

So where have options.modCache, it should be something like:

```js
const id = options.id
options.modCache = modCacheCache[id]  = modCacheCache[id] || {}
```

This insures that if people use the render universal component creation approach, that the same hash is continued to be used client side.

Now, there is one more shitty part: because of how the import can be a function and how the babel plugin works, we won't have the `id` initially (unless manually provided as an option). The `id` is discovered here when using the babel plugin:

https://github.com/faceyspacey/react-universal-component/blob/master/src/requireUniversalModule.js#L199

You will see that ultimately we re-run its calling function `reqiureUniversalModule` multiple times to re-generate the various requireAsync/Sync functions. It's not ideal, and in a future version where we may drop some old lesser-used features we can dial this back and severely ease up the implementation. 

But for now, you basically have to do this:

https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L111

and then add the `id` to the returned object here:

https://github.com/faceyspacey/react-universal-component/blob/master/src/requireUniversalModule.js#L179

**Comment by eldar-gamisoniya** [comment]
I'm planning to play with it this week and make a PR. Not entirely convinced of unique id though, as it adds additional complexity that might be avoided.

**Comment by faceyspacey** [comment]
i think i have the simplest solution: just do no caching on the server! ..so that's like a single `if(isServer)` check in either the load from cache function or the caching function.
