### ISSUE TITLE
Implement loading delay before showing loading component

### ISSUE THREAD

**Issue by tstirrat15** [faceyspacey/react-universal-component#53]
This is something that `react-loadable` has, and it makes sense to me. Flashing a loading screen for an almost-imperceptible amount of time seems clunky.

[Reference](https://github.com/thejameskyle/react-loadable#optsdelay)

**Comment by faceyspacey** [comment]
We did it a different better. It's been explained elsewhere. The delay in Loadable does nothing in reality. It only tricks u all is ok on ur local host where things load fast. In the real world it will take longer and if it takes as long as ur delay u still have the same issue. The way we have implemented is best because it's predictable and doesn't pretend to solve something that isn't solveable.

**Comment by tstirrat15** [comment]
Where is elsewhere?

Is the idea that it's not going to show if it's already been cached, and if it's not, it's going to take longer than the `delay` would be anyway?

**Comment by faceyspacey** [comment]
If it's cached no spinner shows. Preload ur chunks and it never shows. 

Pretty much. Or about the same amount of time which would lead to the same glitch. So by having it set to 300ms at least--when chunks aren't cached--u guarantee a glitch free user experience while being mesmerized by a spinner for a minimum very short period of time.

**Comment by tstirrat15** [comment]
Makes sense. Thank you for explaining!
