### ISSUE TITLE
Silently swallowing errors on server side render leads to unexpected "loading..." from SSR

### ISSUE THREAD

**Issue by jwickens** [faceyspacey/react-universal-component#54]
Hey first of all, great ecosystem! really loving redux-first-router and flush-chunks in particular.

While developing, my components on SSR will often return "loading..." but the client on first render is not "loading..." I've found that this happens whenever I have an error server side (because of some import or another that only works client side). When this happens react-universal silently swallows the error.

I think I've tracked it down to this line:

https://github.com/faceyspacey/react-universal-component/blob/93af44f12bcb842944cbf078e703e3e8f1c51389/src/utils.js#L25

Maybe a console.log or some other way of bubbling out the error so we could be aware of our particular error would cut down on the number of long-winded issues here regarding how to solve the server side "loading..." problem. I like to use the debug utility in my own apps for optionally logging stuff, but i see you're not using that... so not really sure what would be the best way.

**Comment by faceyspacey** [comment]
Glad u like the tools!

In the next release I plan to add a bunch of debugging utilities that u can toggle on and get insights about what went wrong. The problem here is that sometimes it's expected that the require fails. That should how it knows to import it asynchronously. So it would be annoying to see such logging unless explicitly in "debug mode." That has been the thinking. 

I would be open to a console.warn in the mean time that indicates it not necessarily a bug. It would need to not occur if NODE_ENV is development.

**Comment by jwickens** [comment]
Some debugging utilities would be great! It would be stellar if we server rendered the error in a nice html format like react-error-overlay but made it clear it happened on the server and where.

As you say... in the meantime a quick win is a dev only console.log. PR attached.

**Comment by faceyspacey** [comment]
merged. gracias!
