### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by jkettmann** [faceyspacey/react-universal-component#70]
First of all thanks for this great library. It's really easy to use and works fantastic.

I'm building a [boilerplate](https://github.com/jkettmann/universal-react-relay-starter-kit) and ran into this issue during production deployment: `Unexpected token import`, because a dynamic import statement is not compiled.

The [responsible code](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/master/client/Routes.js#L28) is:

```
const getPage = props => import(`./async/${props.page}`)
```

I tried replacing it with the `require.ensure` approach.

```
const getPage = (props, cb) => require.ensure([], require => cb(null, require('./Foo')))
```

but this only gives me `cb is not defined`.

I also tried using the [syntax-dynamic-import](https://babeljs.io/docs/plugins/syntax-dynamic-import/) and [dynamic-import-webpack](https://github.com/airbnb/babel-plugin-dynamic-import-webpack) babel plugin, but then the routes are not resolved anymore.

Could you point me to the right direction on how make this work? Any help is appreciated.

**Comment by faceyspacey** [comment]
I can't quite say for sure what's happening. It wouldn't be `dynamic-import-webpack` that does anything anymore. 

The fact that it's working in development and production indicates it's some other plugin that is overriding it. For example, there's a babel plugin capability to strip comments--if that's there, that would break things as this solution relies on webpack's *magic comments* feature. 

Babel plugins can be finnicky, as the order they are placed does effect things. Your best bet would be to isolate as many things, and remove things until you find the culprit. It sounds like it's another babel plugin that's causing the issue. You may also need the first plugin you mentioned. It's included in `stage-2` for example, and that's why it's not listed as a required dep. Basically most of the latest standard configurations compile correctly, but really custom ones can run into problems. Isolate the different things you're doing until you get to the bottom of it. What's your babelrc?

**Comment by jkettmann** [comment]
Thanks a lot for the reply. I got it working now by using the by using the `babelServer` option of your [babel-plugin-universal-import](https://github.com/faceyspacey/babel-plugin-universal-import#babel-server-or-webpack--2220). I also needed to adjust my build setup a bit. For anyone who might be interested have a look at [the starter kit](https://github.com/jkettmann/universal-react-relay-starter-kit). Following are the steps needed:

- Compile all code with the `babel-server` option set to true like in the [.babelrc](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/master/.babelrc). Important for me was, to also compile the client code. This is because the server needs the compiled client code to create the client bundle for server side rendering. If I don't compile I get errors for ES6 syntax etc. 
- Copy an uncompiled version of the client code to the build directory. This is used by the webpack client production config to create the client bundle to be executed in the browser. In the client webpack config the `babelServer` option is omitted.

Thanks a lot again. Everything is working like a charm now.
