### ISSUE TITLE
Emphasize importance of ordering and synchronous execution for renderToString and flushChunkNames.

### ISSUE THREAD

**Issue by threehams** [faceyspacey/react-universal-component#74]
I don't think I have a solution here, but I'll describe the understanding I've come to about flushChunkNames: it maintains its own global cache, and this can easily persist across requests.

This means that order of execution is extremely important, async rendering is potentially dangerous, and mistakes result in very confusing behavior.

I realized this after I made a mistake and called flushChunkNames before rendering, which resulted in getting chunks intended for previous requests:
```
const chunkNames = flushChunkNames();
getDataFromTree(app).then(() => {
  const content = renderToString(app);
  // chunkNames is now always off by one request, resulting in a server/client checksum mismatch
```

Then, I realized how important it is to flush chunks on errors:
```
try {
  const content = renderToString(app); // error here?
  // or maybe something in between hits an error?
  const chunkNames = flushChunkNames();
} catch(err) {
  // we may get a partial or full list of chunkNames added to the next request, unless
  // we remember to call flushChunksNames() for its side effect of CHUNK_NAMES.clear()
  res.status(500); // etc
}
```

Then, there's the really dangerous stuff which is completely reliant on library internals. I haven't been able to test this for real since it's a tricky race condition, but I've seen each of the parts in isolation.

Example with apollo-client SSR (react-tree-walker and isomorphic-relay work an a similar way, I believe):
```
// This walks the render tree, so it adds chunks to react-universal-component's global 
// cache. What happens when multiple requests come in at once?
getDataFromTree(app).then(() => {
  const content = renderToString(app);
  // Both requests hit getDataFromTree, but the first one wins, so it gets the chunks intended from
  // both requests. The next request gets the correct chunks, because it called renderToString() again.
  const chunkNames = flushChunkNames();
```

Is there any way around the need for the global cache? It feels like it at least deserves a big ⚠️  warning ⚠️  somewhere about the limitations, especially since this could potentially leak code meant for internal use (like an admin system).

**Comment by threehams** [comment]
hm. This seems like it could all be fixed by using a root-level provider and connecting `<Universal>` to context so it can write the cache to an instance rather than to a module-level array, or so it can distinguish between requests (require a unique ID to be passed into the provider per-request). That might completely eliminate this... at the expense of a breaking change, an additional export, and an additional server-only setup step.

**Comment by faceyspacey** [comment]
@threehams I've been meaning to expose a `clear` method so you can just clear it before the actual `renderToString`. The reason we don't want the provider context is friction (for the 80% of users not doing asynchronous 2-pass rendering). It's just one more thing you have to do, and nobody feels comfortable adding endless `<Provider />` components to their tree because of the cognitive overhead of not knowing what's going on inside of them; and in this case it would only be needed on the server. A lot of tools count on node's single thread synchronous blocking execution to do flushing without context (the css-in-jss server-side tools, and many others). 

But yea, the error needs to be accounted for to take this all the way. A perhaps better option is `componentDidCatch`: 

https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html

For clearing, just call `flushChunkNames` twice: 
- immediately before `renderToString()`
- and immediately after

What was flushed [here](https://github.com/apollographql/react-apollo/blob/master/src/getDataFromTree.ts#L73) will just be discarded. 


```js
getDataFromTree(app).then(() => {
  flushChunkNames() // clearing
  const content = renderToString(app); // synchronous - all good
  const chunkNames = flushChunkNames();
```

If you'd like to add a `clear` method as a PR (so that we have an explicit API), you can add it here:

https://github.com/faceyspacey/react-universal-component/blob/master/src/requireUniversalModule.js#L184

and re-export it here:

https://github.com/faceyspacey/react-universal-component/blob/master/server.js

If you do the PR--no pressure--it will also need a readme section in `webpack-flush-chunks` called something like **Handling Asynchronous Rendering & Errors** where both points you brought up should be described.

:)
