### ISSUE TITLE
Css classes are loaded multiple times

### ISSUE THREAD

**Issue by thought2** [faceyspacey/react-universal-component#87]
It looks like sometimes identical css classes are loaded multiple times, while they could have been loaded once inside the base chunk. It's a bit hard to describe, when exactly this happens. Here's our setup.

We have 5 universal components, for which style sheets are loaded async. In some cases we observe that even if several components make use of a class it's not included inside the base chunk.  Beside the minimal overhead we are facing weird css specificity inconsistencies, when the same class is loaded twice.

**Comment by faceyspacey** [comment]
Are you isn't the async option for the extract plugin? It won't work. There are several issues and workarounds in the extract-CSS-chunks-webpack-plugin for this.

**Comment by faceyspacey** [comment]
The `async` option to the common chunk plugin will solve it. There are some additional things that need to be done to take this all the way. It's outlined here:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/47

**Comment by jkettmann** [comment]
I also have this issue when two asynchronously loaded components use a common component. In this case the css from the common component is included in the css bundles of both async modules. This causes weired styling issues, since the bundles overwrite each others styles in some cases. I studied this issue and the ones linked here (and the ones linked there as well) but couldn't find a solution

I tried to use the `async` option like 

```
plugins: [
  new ExtractCssChunks(),
  new webpack.optimize.CommonsChunkPlugin({
    async: true,
    names: ['bootstrap'], // needed to put webpack bootstrap code before chunks
    minChunks: Infinity,
  }),
```

or this

```
plugins: [
  new ExtractCssChunks(),
  new webpack.optimize.CommonsChunkPlugin({
    names: ['bootstrap'], // needed to put webpack bootstrap code before chunks
    filename: '[name].js',
    minChunks: Infinity,
  }),
  new webpack.optimize.CommonsChunkPlugin({
    async: 'common',
    children: true,
    minChunks: 2,
  }),
]
```
With the first approach I don't get `bootstrap.js` anymore. The problem with the duplicate classnames still exists.

With the second approach I get following bundles plus the async modules: `bootstrap.js`, `main.js` and `common-main.js`. `common-main.js` is never loaded by the HTML file though. On the client I get `An error occurred Error: export not found`. I guess, because code that some chunk tries to access is inside common bundle.

Is there any detailed answer, gist or something on how to use CommonsChunkPlugin together with async option and universal components?

**Comment by jkettmann** [comment]
For anybody who has the same issue: This is the config that works for me

```
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'bootstrap',
      filename: '[name].js',
      minChunks: Infinity,
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'main',
      async: 'vendor',
      minChunks: 2,
    }),
    ...
  ]
```

The important part is naming the async chunk `vendor`. This name is by default accepted by [webpack-flush-chunks](https://github.com/faceyspacey/webpack-flush-chunks#options-api). Now I get `bootstrap.js` containing the webpack bootstrap code, `vendor.js` containing all common code used by at least two separate chunks and `main.js`.

**Comment by EdonGashi** [comment]
Hi @jkettmann thanks for this.

I iterated a bit and changed to the following:

bootstrap: webpack entry
vendor: only js from node_modules
main: entry js + entry css + common css >= 2 + common js >=3
bundles: individual js + individual css

```
new webpack.optimize.CommonsChunkPlugin({
  name: 'vendor',
  minChunks: function (module) {
    if (module.resource && (/^.*\.(css|scss)$/).test(module.resource)) {
      return false
    }

    return module.context && module.context.indexOf('node_modules') !== -1
  }
}),
new webpack.optimize.CommonsChunkPlugin({
  name: 'main',
  children: true,
  minChunks: function (module, count) {
    if (module.resource && (/^.*\.(css|scss)$/).test(module.resource)) {
      return count > 1
    }

    return count > 2
  }
}),
new webpack.optimize.CommonsChunkPlugin({
  name: 'bootstrap',
  filename: '[name].js',
  minChunks: Infinity
}),
```

I have yet to test it outside hello worlds and I'll post updates
