### ISSUE TITLE
Key differences between alternatives

### ISSUE THREAD

**Issue by papigers** [faceyspacey/react-universal-component#89]
Hi, just wanted to know what are the main differences between this package and familiar like react-loadable and react-async-component.
Thanks!

**Comment by faceyspacey** [comment]
The primary difference is that this package makes SSR a first class concern. Loadable only recently add support for SSR. `async-component` offers an approach that leads to longer times till interactive (TTI), as it does not send the scripts for dynamic chunks in the initial html sent.

Otherwise, this package has the largest set of options, props, etc.
